Switch to explicit -F for per-instance SSH configs

diff --git a/libexec/panboticon/ssh b/libexec/panboticon/ssh
--- a/libexec/panboticon/ssh
+++ b/libexec/panboticon/ssh
@@ -38,9 +38,16 @@ if [ -z "$1" ]
 then
     boxen >"$TMP/boxen.txt"
     if [ "$(wc -l <"$TMP/boxen.txt")" -eq 1 ]
-    then exec "$SSH" -l "$USER" "$(cat "$TMP/boxen.txt")"
+    then exec "$SSH" -F "$HOME/.ssh/panboticon/$(cat "$TMP/boxen.txt").ssh_config" -l "$USER" "$(cat "$TMP/boxen.txt")"
     else usage 1
     fi
 fi
 
-exec "$SSH" -l "$USER" "$@"
+for A in "$@"
+do
+    if [ -f "$HOME/.ssh/panboticon/$A.ssh_config" ]
+    then exec "$SSH" -F "$HOME/.ssh/panboticon/$A.ssh_config" -l "$USER" "$@"
+    fi
+done
+echo "Could not find the name of a Panboticon instance with an SSH configuration amonst the arguments: $*" >&2
+exit 1
